name: Deploy App

on:
  push:
    branches: [main]
  registry_package:
    types: [published, updated]
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
  pages: write
  id-token: write
  packages: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      container: ${{ steps.set-vars.outputs.container }}
    steps:
      - id: set-vars
        run: echo "container=$(echo 'ghcr.io/${{ github.repository }}:main' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

  render:
    needs: setup
    runs-on: ubuntu-latest
    container: ${{ needs.setup.outputs.container }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          Rscript -e "shinylive::export(appdir = 'shiny', destdir = 'deploy')"

      - name: Setup GitHub Pages
        id: pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Upload artifact for Pages Deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./deploy

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: render
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
