name: Python Environment Setup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Choose the version you need

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test installation of linkml
      run: |
        linkml-validate --version
    - name: Validate data.yml
      id: validate
      run: |
        validation_output=$(linkml-validate -s schema.yml data.yml 2>&1)
        echo "$validation_output"
        echo "validation_output<<EOF" >> $GITHUB_ENV
        echo "$validation_output" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      continue-on-error: true

    - name: Add comment
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const validationOutput = process.env.validation_output;
          const errorMessage = validationOutput.split('\n').find(line => line.startsWith('Error:'));
          if (errorMessage) {
            const issue_number = context.issue.number;
            const comment = { owner: context.repo.owner, repo: context.repo.repo, issue_number: issue_number, body: errorMessage };
            github.rest.issues.createComment(comment);
          }